# -----------------------------
# Server configuration
# -----------------------------
server.port=${PORT:8081}  # Utilise le port fourni par l'environnement ou 8081 par défaut

# -----------------------------
# Database configuration (Supabase)
# -----------------------------
spring.datasource.url=jdbc:postgresql://db.kufpkddgxlwrdfbamaiq.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Noeantares.2003

# -----------------------------
# JPA / Hibernate
# -----------------------------
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update